//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3615
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// 元のファイル名:
// 生成日: 2010/08/16 19:01:37
namespace testfdb_cs
{
    
    /// <summary>
    /// スキーマの FileDataModelContainer にはコメントがありません。
    /// </summary>
    public partial class FileDataModelContainer : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// アプリケーション構成ファイルの 'FileDataModelContainer' セクションにある接続文字列を使用して新しい FileDataModelContainer オブジェクトを初期化します。
        /// </summary>
        public FileDataModelContainer() : 
                base("name=FileDataModelContainer", "FileDataModelContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 新しい FileDataModelContainer オブジェクトを初期化します。
        /// </summary>
        public FileDataModelContainer(string connectionString) : 
                base(connectionString, "FileDataModelContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 新しい FileDataModelContainer オブジェクトを初期化します。
        /// </summary>
        public FileDataModelContainer(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "FileDataModelContainer")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// スキーマの FileTable にはコメントがありません。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<FileTable> FileTable
        {
            get
            {
                if ((this._FileTable == null))
                {
                    this._FileTable = base.CreateQuery<FileTable>("[FileTable]");
                }
                return this._FileTable;
            }
        }
        private global::System.Data.Objects.ObjectQuery<FileTable> _FileTable;
        /// <summary>
        /// スキーマの TagTable にはコメントがありません。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TagTable> TagTable
        {
            get
            {
                if ((this._TagTable == null))
                {
                    this._TagTable = base.CreateQuery<TagTable>("[TagTable]");
                }
                return this._TagTable;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TagTable> _TagTable;
        /// <summary>
        /// スキーマの TaggedFileTable にはコメントがありません。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TaggedFileTable> TaggedFileTable
        {
            get
            {
                if ((this._TaggedFileTable == null))
                {
                    this._TaggedFileTable = base.CreateQuery<TaggedFileTable>("[TaggedFileTable]");
                }
                return this._TaggedFileTable;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TaggedFileTable> _TaggedFileTable;
        /// <summary>
        /// スキーマの FileTable にはコメントがありません。
        /// </summary>
        public void AddToFileTable(FileTable fileTable)
        {
            base.AddObject("FileTable", fileTable);
        }
        /// <summary>
        /// スキーマの TagTable にはコメントがありません。
        /// </summary>
        public void AddToTagTable(TagTable tagTable)
        {
            base.AddObject("TagTable", tagTable);
        }
        /// <summary>
        /// スキーマの TaggedFileTable にはコメントがありません。
        /// </summary>
        public void AddToTaggedFileTable(TaggedFileTable taggedFileTable)
        {
            base.AddObject("TaggedFileTable", taggedFileTable);
        }
    }
    /// <summary>
    /// スキーマの FileDataModel.FileTable にはコメントがありません。
    /// </summary>
    /// <KeyProperties>
    /// guid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="FileDataModel", Name="FileTable")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FileTable : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 新しい FileTable オブジェクトを作成します。
        /// </summary>
        /// <param name="guid">guid の初期値。</param>
        /// <param name="name">name の初期値。</param>
        /// <param name="comment">comment の初期値。</param>
        public static FileTable CreateFileTable(string guid, string name, string comment)
        {
            FileTable fileTable = new FileTable();
            fileTable.guid = guid;
            fileTable.name = name;
            fileTable.comment = comment;
            return fileTable;
        }
        /// <summary>
        /// スキーマのプロパティ guid にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string guid
        {
            get
            {
                return this._guid;
            }
            set
            {
                this.OnguidChanging(value);
                this.ReportPropertyChanging("guid");
                this._guid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("guid");
                this.OnguidChanged();
            }
        }
        private string _guid;
        partial void OnguidChanging(string value);
        partial void OnguidChanged();
        /// <summary>
        /// スキーマのプロパティ name にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// スキーマのプロパティ comment にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this._comment;
            }
            set
            {
                this.OncommentChanging(value);
                this.ReportPropertyChanging("comment");
                this._comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("comment");
                this.OncommentChanged();
            }
        }
        private string _comment;
        partial void OncommentChanging(string value);
        partial void OncommentChanged();
    }
    /// <summary>
    /// スキーマの FileDataModel.TagTable にはコメントがありません。
    /// </summary>
    /// <KeyProperties>
    /// tag
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="FileDataModel", Name="TagTable")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TagTable : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 新しい TagTable オブジェクトを作成します。
        /// </summary>
        /// <param name="tag">tag の初期値。</param>
        public static TagTable CreateTagTable(string tag)
        {
            TagTable tagTable = new TagTable();
            tagTable.tag = tag;
            return tagTable;
        }
        /// <summary>
        /// スキーマのプロパティ tag にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string tag
        {
            get
            {
                return this._tag;
            }
            set
            {
                this.OntagChanging(value);
                this.ReportPropertyChanging("tag");
                this._tag = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("tag");
                this.OntagChanged();
            }
        }
        private string _tag;
        partial void OntagChanging(string value);
        partial void OntagChanged();
    }
    /// <summary>
    /// スキーマの FileDataModel.TaggedFileTable にはコメントがありません。
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="FileDataModel", Name="TaggedFileTable")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TaggedFileTable : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 新しい TaggedFileTable オブジェクトを作成します。
        /// </summary>
        /// <param name="guid">guid の初期値。</param>
        /// <param name="tag">tag の初期値。</param>
        /// <param name="id">id の初期値。</param>
        public static TaggedFileTable CreateTaggedFileTable(string guid, string tag, long id)
        {
            TaggedFileTable taggedFileTable = new TaggedFileTable();
            taggedFileTable.guid = guid;
            taggedFileTable.tag = tag;
            taggedFileTable.id = id;
            return taggedFileTable;
        }
        /// <summary>
        /// スキーマのプロパティ guid にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string guid
        {
            get
            {
                return this._guid;
            }
            set
            {
                this.OnguidChanging(value);
                this.ReportPropertyChanging("guid");
                this._guid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("guid");
                this.OnguidChanged();
            }
        }
        private string _guid;
        partial void OnguidChanging(string value);
        partial void OnguidChanged();
        /// <summary>
        /// スキーマのプロパティ tag にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string tag
        {
            get
            {
                return this._tag;
            }
            set
            {
                this.OntagChanging(value);
                this.ReportPropertyChanging("tag");
                this._tag = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("tag");
                this.OntagChanged();
            }
        }
        private string _tag;
        partial void OntagChanging(string value);
        partial void OntagChanged();
        /// <summary>
        /// スキーマのプロパティ id にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
    }
}
