//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3615
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("FileDataModel", "FileTableTagTable", "FileTable", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(testfdb_cs.FileTable), "TagTable", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(testfdb_cs.TagTable))]

// 元のファイル名:
// 生成日: 2010/08/18 14:44:14
namespace testfdb_cs
{
    
    /// <summary>
    /// スキーマの FileDataModelContainer にはコメントがありません。
    /// </summary>
    public partial class FileDataModelContainer : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// アプリケーション構成ファイルの 'FileDataModelContainer' セクションにある接続文字列を使用して新しい FileDataModelContainer オブジェクトを初期化します。
        /// </summary>
        public FileDataModelContainer() : 
                base("name=FileDataModelContainer", "FileDataModelContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 新しい FileDataModelContainer オブジェクトを初期化します。
        /// </summary>
        public FileDataModelContainer(string connectionString) : 
                base(connectionString, "FileDataModelContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 新しい FileDataModelContainer オブジェクトを初期化します。
        /// </summary>
        public FileDataModelContainer(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "FileDataModelContainer")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// スキーマの FileTable にはコメントがありません。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<FileTable> FileTable
        {
            get
            {
                if ((this._FileTable == null))
                {
                    this._FileTable = base.CreateQuery<FileTable>("[FileTable]");
                }
                return this._FileTable;
            }
        }
        private global::System.Data.Objects.ObjectQuery<FileTable> _FileTable;
        /// <summary>
        /// スキーマの TagTable にはコメントがありません。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TagTable> TagTable
        {
            get
            {
                if ((this._TagTable == null))
                {
                    this._TagTable = base.CreateQuery<TagTable>("[TagTable]");
                }
                return this._TagTable;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TagTable> _TagTable;
        /// <summary>
        /// スキーマの FileTable にはコメントがありません。
        /// </summary>
        public void AddToFileTable(FileTable fileTable)
        {
            base.AddObject("FileTable", fileTable);
        }
        /// <summary>
        /// スキーマの TagTable にはコメントがありません。
        /// </summary>
        public void AddToTagTable(TagTable tagTable)
        {
            base.AddObject("TagTable", tagTable);
        }
    }
    /// <summary>
    /// スキーマの FileDataModel.FileTable にはコメントがありません。
    /// </summary>
    /// <KeyProperties>
    /// filetableid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="FileDataModel", Name="FileTable")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FileTable : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 新しい FileTable オブジェクトを作成します。
        /// </summary>
        /// <param name="filetableid">filetableid の初期値。</param>
        /// <param name="guid">guid の初期値。</param>
        /// <param name="name">name の初期値。</param>
        /// <param name="ext">ext の初期値。</param>
        /// <param name="comment">comment の初期値。</param>
        /// <param name="createtime">createtime の初期値。</param>
        public static FileTable CreateFileTable(long filetableid, string guid, string name, string ext, string comment, global::System.DateTime createtime)
        {
            FileTable fileTable = new FileTable();
            fileTable.filetableid = filetableid;
            fileTable.guid = guid;
            fileTable.name = name;
            fileTable.ext = ext;
            fileTable.comment = comment;
            fileTable.createtime = createtime;
            return fileTable;
        }
        /// <summary>
        /// スキーマのプロパティ filetableid にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long filetableid
        {
            get
            {
                return this._filetableid;
            }
            set
            {
                this.OnfiletableidChanging(value);
                this.ReportPropertyChanging("filetableid");
                this._filetableid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("filetableid");
                this.OnfiletableidChanged();
            }
        }
        private long _filetableid;
        partial void OnfiletableidChanging(long value);
        partial void OnfiletableidChanged();
        /// <summary>
        /// スキーマのプロパティ guid にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string guid
        {
            get
            {
                return this._guid;
            }
            set
            {
                this.OnguidChanging(value);
                this.ReportPropertyChanging("guid");
                this._guid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("guid");
                this.OnguidChanged();
            }
        }
        private string _guid;
        partial void OnguidChanging(string value);
        partial void OnguidChanged();
        /// <summary>
        /// スキーマのプロパティ name にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// スキーマのプロパティ ext にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ext
        {
            get
            {
                return this._ext;
            }
            set
            {
                this.OnextChanging(value);
                this.ReportPropertyChanging("ext");
                this._ext = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ext");
                this.OnextChanged();
            }
        }
        private string _ext;
        partial void OnextChanging(string value);
        partial void OnextChanged();
        /// <summary>
        /// スキーマのプロパティ comment にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this._comment;
            }
            set
            {
                this.OncommentChanging(value);
                this.ReportPropertyChanging("comment");
                this._comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("comment");
                this.OncommentChanged();
            }
        }
        private string _comment;
        partial void OncommentChanging(string value);
        partial void OncommentChanged();
        /// <summary>
        /// スキーマのプロパティ createtime にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime createtime
        {
            get
            {
                return this._createtime;
            }
            set
            {
                this.OncreatetimeChanging(value);
                this.ReportPropertyChanging("createtime");
                this._createtime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("createtime");
                this.OncreatetimeChanged();
            }
        }
        private global::System.DateTime _createtime;
        partial void OncreatetimeChanging(global::System.DateTime value);
        partial void OncreatetimeChanged();
        /// <summary>
        /// スキーマの TagTable にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("FileDataModel", "FileTableTagTable", "TagTable")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TagTable> TagTable
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TagTable>("FileDataModel.FileTableTagTable", "TagTable");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TagTable>("FileDataModel.FileTableTagTable", "TagTable", value);
                }
            }
        }
    }
    /// <summary>
    /// スキーマの FileDataModel.TagTable にはコメントがありません。
    /// </summary>
    /// <KeyProperties>
    /// tagtableid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="FileDataModel", Name="TagTable")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TagTable : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 新しい TagTable オブジェクトを作成します。
        /// </summary>
        /// <param name="tagtableid">tagtableid の初期値。</param>
        /// <param name="tag">tag の初期値。</param>
        public static TagTable CreateTagTable(long tagtableid, string tag)
        {
            TagTable tagTable = new TagTable();
            tagTable.tagtableid = tagtableid;
            tagTable.tag = tag;
            return tagTable;
        }
        /// <summary>
        /// スキーマのプロパティ tagtableid にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long tagtableid
        {
            get
            {
                return this._tagtableid;
            }
            set
            {
                this.OntagtableidChanging(value);
                this.ReportPropertyChanging("tagtableid");
                this._tagtableid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("tagtableid");
                this.OntagtableidChanged();
            }
        }
        private long _tagtableid;
        partial void OntagtableidChanging(long value);
        partial void OntagtableidChanged();
        /// <summary>
        /// スキーマのプロパティ tag にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string tag
        {
            get
            {
                return this._tag;
            }
            set
            {
                this.OntagChanging(value);
                this.ReportPropertyChanging("tag");
                this._tag = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("tag");
                this.OntagChanged();
            }
        }
        private string _tag;
        partial void OntagChanging(string value);
        partial void OntagChanged();
        /// <summary>
        /// スキーマの FileTable にはコメントがありません。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("FileDataModel", "FileTableTagTable", "FileTable")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public FileTable FileTable
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FileTable>("FileDataModel.FileTableTagTable", "FileTable").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FileTable>("FileDataModel.FileTableTagTable", "FileTable").Value = value;
            }
        }
        /// <summary>
        /// スキーマの FileTable にはコメントがありません。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<FileTable> FileTableReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<FileTable>("FileDataModel.FileTableTagTable", "FileTable");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<FileTable>("FileDataModel.FileTableTagTable", "FileTable", value);
                }
            }
        }
    }
}
