var browser =
{
	ATTRIBUTE_NODE:2,
	CDATA_SECTION_NODE:4,
	COMMENT_NODE:8,
	DOCUMENT_FRAGMENT_NODE:11,
	DOCUMENT_NODE:9,
	DOCUMENT_POSITION_CONTAINED_BY:16,
	DOCUMENT_POSITION_CONTAINS:8,
	DOCUMENT_POSITION_DISCONNECTED:1,
	DOCUMENT_POSITION_FOLLOWING:4,
	DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC:32,
	DOCUMENT_POSITION_PRECEDING:2,
	DOCUMENT_TYPE_NODE:10,
	ELEMENT_NODE:1,
	ENTITY_NODE:6,
	ENTITY_REFERENCE_NODE:5,
	NOTATION_NODE:12,
	PROCESSING_INSTRUCTION_NODE:7,
	TEXT_NODE:3,
	_AUTOSCROLL_SNAP:10,
	_AUTOSCROLL_SPEED:3,
	_autoScrollNeedsCleanup:false,
	_autoScrollPopup:null,
	_autoScrollTimer:null,
	_contentWindow:[object XPCNativeWrapper [object Window]],
	_docShell:[xpconnect wrapped (nsISupports, nsIDocShell, nsIInterfaceRequestor, nsIWebNavigation, nsIWebProgress, nsIDocShellHistory, nsIDocumentLoader, nsIRequestObserver)],
	_fastFind:[xpconnect wrapped nsITypeAheadFind],
	_mStrBundle:null,
	_screenX:null,
	_screenY:null,
	_scrollingView:null,
	_startX:null,
	_startY:null,
	_userTypedValue:null,
	_webBrowserFind:null,
	_webNavigation:[xpconnect wrapped (nsISupports, nsIDocShell, nsIInterfaceRequestor, nsIWebNavigation, nsIWebProgress, nsIDocShellHistory, nsIDocumentLoader, nsIRequestObserver)],
	accessibleType:1,
	align:,
	allowEvents:false,
	attributes:[object NamedNodeMap],
	autoscrollEnabled:true,
	baseURI:chrome://browser/content/browser.xul,
	boxObject:[object BoxObject],
	builder:null,
	canGoBack:false,
	canGoForward:false,
	childElementCount:0,
	childNodes:[object NodeList],
	children:[object HTMLCollection],
	chrome:[object Object],
	classList:,
	className:,
	clientHeight:301,
	clientLeft:0,
	clientTop:0,
	clientWidth:799,
	collapsed:false,
	contentDocument:[object XPCNativeWrapper [object HTMLDocument]],
	contentPrincipal:[object XPCNativeWrapper [xpconnect wrapped (nsISupports, nsIPrincipal, nsISerializable)]],
	contentTitle:Mozilla Firefox スタートページ,
	contentViewerEdit:[xpconnect wrapped (nsISupports, nsIContentViewer, nsIMarkupDocumentViewer, nsIContentViewerEdit)],
	contentViewerFile:[xpconnect wrapped (nsISupports, nsIContentViewer, nsIMarkupDocumentViewer, nsIContentViewerEdit, nsIContentViewerFile)],
	contentWindow:[object XPCNativeWrapper [object Window]],
	contextMenu:contentAreaContextMenu,
	controllers:[object XULControllers],
	currentURI:[xpconnect wrapped nsIURI],
	database:null,
	datasources:,
	dir:,
	docShell:[xpconnect wrapped (nsISupports, nsIDocShell, nsIInterfaceRequestor, nsIWebNavigation, nsIWebProgress, nsIDocShellHistory, nsIDocumentLoader, nsIRequestObserver)],
	documentCharsetInfo:[xpconnect wrapped nsIDocumentCharsetInfo],
	engines:null,
	fastFind:[xpconnect wrapped nsITypeAheadFind],
	feeds:null,
	firstChild:null,
	firstElementChild:null,
	flex:1,
	flexGroup:,
	frameListener:[object Object],
	height:,
	hidden:false,
	homePage:http://www.mozilla.org/,
	id:,
	isShowingMessage:false,
	isSystemPage:undefined,
	lastChild:null,
	lastElementChild:null,
	lastURI:[xpconnect wrapped nsIURI],
	left:,
	localName:browser,
	mAtomService:[xpconnect wrapped nsIAtomService],
	mDestroyed:false,
	mDragDropHandler:[xpconnect wrapped nsIDragDropHandler],
	mFormFillAttached:true,
	mIconURL:http://www.google.co.jp/favicon.ico,
	mPrefs:[xpconnect wrapped nsIPrefBranch],
	mStrBundle:[xpconnect wrapped nsIStringBundle],
	markupDocumentViewer:[xpconnect wrapped (nsISupports, nsIContentViewer, nsIMarkupDocumentViewer)],
	maxHeight:,
	maxWidth:,
	menu:,
	minHeight:,
	minWidth:,
	missingPlugins:null,
	namespaceURI:http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul,
	nextElementSibling:null,
	nextSibling:null,
	nodeName:xul:browser,
	nodeType:1,
	nodeValue:null,
	observes:,
	ordinal:,
	orient:,
	ownerDocument:[object XULDocument],
	pack:,
	pageReport:null,
	parentNode:[object XULElement],
	persist:,
	preferences:[xpconnect wrapped (nsISupports, nsIPrefBranch2, nsIPrefService, nsIPrefBranch)],
	prefix:xul,
	previousElementSibling:null,
	previousSibling:null,
	ref:,
	resource:null,
	scrollHeight:301,
	scrollLeft:0,
	scrollTop:0,
	scrollWidth:799,
	securityUI:[xpconnect wrapped (nsISupports, nsISecureBrowserUI, nsISSLStatusProvider)],
	sessionHistory:[xpconnect wrapped nsISHistory],
	showFirebug:true,
	statusText:,
	style:[object CSSStyleDeclaration],
	tagName:xul:browser,
	textContent:,
	tooltip:aHTMLTooltip,
	tooltipText:,
	top:,
	userTypedClear:0,
	userTypedValue:null,
	webBrowserFind:[xpconnect wrapped nsIWebBrowserFind],
	webNavigation:[xpconnect wrapped (nsISupports, nsIDocShell, nsIInterfaceRequestor, nsIWebNavigation, nsIWebProgress, nsIDocShellHistory, nsIDocumentLoader, nsIRequestObserver)],
	webProgress:[xpconnect wrapped (nsISupports, nsIDocShell, nsIInterfaceRequestor, nsIWebNavigation, nsIWebProgress, nsIDocShellHistory, nsIDocumentLoader, nsIRequestObserver)],
	width:,
	_accelerate:function (curr, start){},
	_createAutoScrollPopup:function (){},
	_roundToZero:function (num){},
	addEventListener:function (){},
	addProgressListener:function (aListener){},
	appendChild:function (){},
	attachFormFill:function (){},
	autoScrollLoop:function (){},
	blur:function (){},
	click:function (){},
	cloneNode:function (){},
	compareDocumentPosition:function (){},
	destroy:function (){},
	detachFormFill:function (){},
	dispatchEvent:function (){},
	doCommand:function (){},
	findChildShell:function (aDocShell, aSoughtURI){},
	focus:function (){},
	getAttribute:function (){},
	getAttributeNS:function (){},
	getAttributeNode:function (){},
	getAttributeNodeNS:function (){},
	getBoundingClientRect:function (){},
	getClientRects:function (){},
	getElementsByAttribute:function (){},
	getElementsByAttributeNS:function (){},
	getElementsByClassName:function (){},
	getElementsByTagName:function (){},
	getElementsByTagNameNS:function (){},
	getFeature:function (){},
	getTabBrowser:function (){},
	getUserData:function (){},
	goBack:function (){},
	goForward:function (){},
	goHome:function (){},
	gotoIndex:function (aIndex){},
	handleEvent:function (aEvent){},
	hasAttribute:function (){},
	hasAttributeNS:function (){},
	hasAttributes:function (){},
	hasChildNodes:function (){},
	insertBefore:function (){},
	isAutoscrollBlocker:function (node){},
	isDefaultNamespace:function (){},
	isEqualNode:function (){},
	isSameNode:function (){},
	isSupported:function (){},
	loadURI:function (aURI, aReferrerURI, aCharset){},
	loadURIWithFlags:function (aURI, aFlags, aReferrerURI, aCharset, aPostData){},
	lookupNamespaceURI:function (){},
	lookupPrefix:function (){},
	mozMatchesSelector:function (){},
	normalize:function (){},
	observe:function (aSubject, aTopic, aState){},
	onPageHide:function (aEvent){},
	onPageShow:function (aEvent){},
	onPopupBlocked:function (evt){},
	querySelector:function (){},
	querySelectorAll:function (){},
	reload:function (){},
	reloadWithFlags:function (aFlags){},
	removeAttribute:function (){},
	removeAttributeNS:function (){},
	removeAttributeNode:function (){},
	removeChild:function (){},
	removeEventListener:function (){},
	removeProgressListener:function (aListener){},
	replaceChild:function (){},
	setAttribute:function (){},
	setAttributeNS:function (){},
	setAttributeNode:function (){},
	setAttributeNodeNS:function (){},
	setUserData:function (){},
	startScroll:function (event){},
	stop:function (){},
	stopScroll:function (){},
	swapDocShells:function (aOtherBrowser){},
	updatePageReport:function (){}
}
var gBrowser =
{
	ATTRIBUTE_NODE:2,
	CDATA_SECTION_NODE:4,
	COMMENT_NODE:8,
	DOCUMENT_FRAGMENT_NODE:11,
	DOCUMENT_NODE:9,
	DOCUMENT_POSITION_CONTAINED_BY:16,
	DOCUMENT_POSITION_CONTAINS:8,
	DOCUMENT_POSITION_DISCONNECTED:1,
	DOCUMENT_POSITION_FOLLOWING:4,
	DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC:32,
	DOCUMENT_POSITION_PRECEDING:2,
	DOCUMENT_TYPE_NODE:10,
	ELEMENT_NODE:1,
	ENTITY_NODE:6,
	ENTITY_REFERENCE_NODE:5,
	NOTATION_NODE:12,
	PROCESSING_INSTRUCTION_NODE:7,
	TEXT_NODE:3,
	_autoScrollPopup:[object XULElement],
	_blockDblClick:false,
	_browsers:[object XULElement],
	_fastFind:[xpconnect wrapped nsITypeAheadFind],
	_keyEventHandler:[object Object],
	_lastRelatedTab:null,
	_previewMode:false,
	_removingTabs:,
	_supportedLinkDropTypes:"", //text/x-moz-url,text/uri-list,text/plain,application/x-moz-file,
	_windowIsClosing:false,
	align:null,
	allowEvents:false,
	arrowKeysShouldWrap:false,
	attributes:[object NamedNodeMap],
	baseURI:chrome://browser/content/browser.xul,
	boxObject:[object BoxObject],
	browsers:[object XULElement],
	builder:null,
	canGoBack:false,
	canGoForward:false,
	childElementCount:1,
	childNodes:[object NodeList],
	children:[object HTMLCollection],
	classList:null,
	className:null,
	clientHeight:330,
	clientLeft:0,
	clientTop:0,
	clientWidth:799,
	collapsed:false,
	contentDocument:[object XPCNativeWrapper [object HTMLDocument]],
	contentPrincipal:[object XPCNativeWrapper [xpconnect wrapped (nsISupports, nsIPrincipal, nsISerializable)]],
	contentTitle:"",//Mozilla Firefox スタートページ,
	contentViewerEdit:[xpconnect wrapped (nsISupports, nsIContentViewer, nsIMarkupDocumentViewer, nsIContentViewerEdit)],
	contentViewerFile:[xpconnect wrapped (nsISupports, nsIContentViewer, nsIMarkupDocumentViewer, nsIContentViewerEdit, nsIContentViewerFile)],
	contentWindow:[object XPCNativeWrapper [object Window]],
	contextMenu:,
	controllers:[object XULControllers],
	currentURI:[xpconnect wrapped nsIURI],
	database:null,
	datasources:null,
	dir:null,
	docShell:[xpconnect wrapped (nsISupports, nsIDocShell, nsIInterfaceRequestor, nsIWebNavigation, nsIWebProgress, nsIDocShellHistory, nsIRequestObserver, nsIDocumentLoader)],
	documentCharsetInfo:[xpconnect wrapped nsIDocumentCharsetInfo],
	fastFind:[xpconnect wrapped nsITypeAheadFind],
	firstChild:[object XULElement],
	firstElementChild:[object XULElement],
	flex:1,
	flexGroup:null,
	height:0,
	hidden:false,
	homePage:http://www.mozilla.org/,
	id:content,
	lastChild:[object XULElement],
	lastElementChild:[object XULElement],
	left:0,
	localName:tabbrowser,
	mAddProgressListenerWasCalled:true,
	mContextTab:null,
	mCurrentBrowser:[object XULElement],
	mCurrentTab:[object XULElement],
	mDragOverDelay:350,
	mDragTime:0,
	mFaviconService:[xpconnect wrapped nsIFaviconService],
	mIsBusy:false,
	mPanelContainer:[object XULElement],
	mPrefs:[xpconnect wrapped nsIPrefBranch],
	mProgressListeners:[object Object],[object Object],[object Object],
	mStringBundle:[object XULElement],
	mStrip:[object XULElement],
	mTabBox:[object XULElement],
	mTabContainer:[object XULElement],
	mTabDropIndicatorBar:[object XULElement],
	mTabFilters:[xpconnect wrapped nsIWebProgress],
	mTabListeners:[object Object],
	mTabbedMode:true,
	mTabs:[object NodeList],
	mTabsProgressListeners:[object Object],
	mURIFixup:[xpconnect wrapped nsIURIFixup],
	mUndoCloseTabMenuItem:[object XULElement],
	markupDocumentViewer:[xpconnect wrapped (nsISupports, nsIContentViewer, nsIMarkupDocumentViewer)],
	maxHeight:0,
	maxWidth:0,
	menu:null,
	minHeight:0,
	minWidth:0,
	namespaceURI:"", //http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul,
	nextElementSibling:[object XULElement],
	nextSibling:[object XULElement],
	nodeName:tabbrowser,
	nodeType:1,
	nodeValue:null,
	observes:null,
	ordinal:null,
	orient:null,
	ownerDocument:[object XULDocument],
	pack:null,
	pageReport:null,
	parentNode:[object XULElement],
	persist:null,
	prefix:null,
	previousElementSibling:null,
	previousSibling:null,
	ref:null,
	resource:[xpconnect wrapped nsIRDFResource],
	scrollHeight:330,
	scrollLeft:0,
	scrollTop:0,
	scrollWidth:799,
	securityUI:[xpconnect wrapped (nsISupports, nsISecureBrowserUI, nsISSLStatusProvider)],
	selectedBrowser:[object XULElement],
	selectedTab:[object XULElement],
	sessionHistory:[xpconnect wrapped nsISHistory],
	statusText:,
	style:[object CSSStyleDeclaration],
	tabContainer:[object XULElement],
	tagName:tabbrowser,
	textContent:"",
	tooltip:"",
	tooltipText:"",
	top:0,
	userTypedClear:0,
	userTypedValue:null,
	webBrowserFind:[xpconnect wrapped nsIWebBrowserFind],
	webNavigation:[xpconnect wrapped (nsISupports, nsIDocShell, nsIInterfaceRequestor, nsIWebNavigation, nsIWebProgress, nsIDocShellHistory, nsIRequestObserver, nsIDocumentLoader)],
	webProgress:[xpconnect wrapped (nsISupports, nsIDocShell, nsIInterfaceRequestor, nsIWebNavigation, nsIWebProgress, nsIDocShellHistory, nsIRequestObserver, nsIDocumentLoader)],
	width:0,
	
	_beginRemoveTab:function (aTab, aTabWillBeMoved, aCloseWindowWithLastTab, aCloseWindowFastpath){},
	_blurTab:function (aTab){},
	_endRemoveTab:function (args){},
	_onDragEnd:function (aEvent){},
	_onDragLeave:function (aEvent){},
	_onDragOver:function (aEvent){},
	_onDragStart:function (aEvent){},
	_onDrop:function (aEvent){},
	_setEffectAllowedForDataTransfer:function (aEvent){},
	addEventListener:function (){},
	addProgressListener:function (aListener, aMask){},
	addTab:function (aURI, aReferrerURI, aCharset, aPostData, aOwner, aAllowThirdPartyFixup){},
	addTabsProgressListener:function (aListener){},
	appendChild:function (){},
	attachFormFill:function (){},
	blur:function (){},
	click:function (){},
	cloneNode:function (){},
	compareDocumentPosition:function (){},
	createTooltip:function (event){},
	detachFormFill:function (){},
	dispatchEvent:function (){},
	doCommand:function (){},
	dragDropSecurityCheck:function (aEvent, aDragSession, aUri){},
	duplicateTab:function (aTab){},
	enterTabbedMode:function (){},
	focus:function (){},
	getAttribute:function (){},
	getAttributeNS:function (){},
	getAttributeNode:function (){},
	getAttributeNodeNS:function (){},
	getBoundingClientRect:function (){},
	getBrowserAtIndex:function (aIndex){},
	getBrowserForDocument:function (aDocument){},
	getBrowserForTab:function (aTab){},
	getBrowserIndexForDocument:function (aDocument){},
	getClientRects:function (){},
	getElementsByAttribute:function (){},
	getElementsByAttributeNS:function (){},
	getElementsByClassName:function (){},
	getElementsByTagName:function (){},
	getElementsByTagNameNS:function (){},
	getFeature:function (){},
	getNewIndex:function (aEvent){},
	getNotificationBox:function (aBrowser){},
	getStripVisibility:function (){},
	getUserData:function (){},
	goBack:function (){},
	goForward:function (){},
	goHome:function (){},
	gotoIndex:function (aIndex){},
	hasAttribute:function (){},
	hasAttributeNS:function (){},
	hasAttributes:function (){},
	hasChildNodes:function (){},
	insertBefore:function (){},
	isDefaultNamespace:function (){},
	isEqualNode:function (){},
	isFailedIcon:function (aURI){},
	isSameNode:function (){},
	isSupported:function (){},
	loadOneTab:function (aURI, aReferrerURI, aCharset, aPostData, aLoadInBackground, aAllowThirdPartyFixup){},
	loadTabs:function (aURIs, aLoadInBackground, aReplace){},
	loadURI:function (aURI, aReferrerURI, aCharset){},
	loadURIWithFlags:function (aURI, aFlags, aReferrerURI, aCharset, aPostData){},
	lookupNamespaceURI:function (){},
	lookupPrefix:function (){},
	mTabProgressListener:function (aTab, aBrowser, aStartsBlank){},
	moveTabBackward:function (){},
	moveTabForward:function (){},
	moveTabOver:function (aEvent){},
	moveTabTo:function (aTab, aIndex){},
	moveTabToEnd:function (){},
	moveTabToStart:function (){},
	mozMatchesSelector:function (){},
	normalize:function (){},
	onTabBarDblClick:function (aEvent){},
	onTabClick:function (event){},
	onTitleChanged:function (evt){},
	previewTab:function (aTab, aCallback){},
	querySelector:function (){},
	querySelectorAll:function (){},
	reload:function (){},
	reloadAllTabs:function (){},
	reloadTab:function (aTab){},
	reloadWithFlags:function (aFlags){},
	removeAllTabsBut:function (aTab){},
	removeAttribute:function (){},
	removeAttributeNS:function (){},
	removeAttributeNode:function (){},
	removeChild:function (){},
	removeCurrentTab:function (){},
	removeEventListener:function (){},
	removeProgressListener:function (aListener){},
	removeTab:function (aTab){},
	removeTabsProgressListener:function (aListener){},
	replaceChild:function (){},
	replaceTabWithWindow:function (aTab){},
	selectTabAtIndex:function (aIndex, aEvent){},
	setAttribute:function (){},
	setAttributeNS:function (){},
	setAttributeNode:function (){},
	setAttributeNodeNS:function (){},
	setIcon:function (aTab, aURI){},
	setStripVisibilityTo:function (aShow){},
	setTabTitle:function (aTab){},
	setTabTitleLoading:function (aTab){},
	setUserData:function (){},
	shouldLoadFavIcon:function (aURI){},
	stop:function (){},
	swapBrowsersAndCloseOther:function (aOurTab, aOtherTab){},
	updateCurrentBrowser:function (aForceUpdate){},
	updateIcon:function (aTab){},
	updatePopupMenu:function (aPopupMenu){},
	updateTitlebar:function (){},
	useDefaultIcon:function (aTab){},
	warnAboutClosingTabs:function (aAll){}
}